export const suggestionCorpus = {
	T: {
		To: ['Opening Stock', 'Purchase', 'Carriage Inward', 'Gross Profit'],
		By: ['Sales', 'Closing Stock'],
	},
	PL: {
		To: [
			'Rent',
			'Salary',
			'Electric Charges',
			'Printing & Stationary',
			'Accounting Charges',
			'Telephone Charges',
			'Depreciation',
			'Furniture @ 10%',
			'Lighting & Fitting @ 15%',
		],
		By: ['Gross Profit', 'Interest on Savings', 'Interest on Deposits'],
	},
	BS: {
		To: [
			'Capital Account',
			'Opening Balance',
			'Net Profit',
			'Less. Cash Drawing',
			'Less. LIP',
			'Sundry Creditors',
			'Loans',
		],
		By: [
			'Furniture',
			'Lighting & Fittings',
			'Plant & Machineries',
			'Opening Balance',
			'Last A/c',
			'Dep @ 10%',
			'Dep @ 15%',
			'Sundry Debtors',
			'Closing Stock',
			'Advances and Investment',
			'Cash at Bank',
			'<BankName>, <BranchName>, <AccountType> A/c - <AccountNumber>',
			'Cash in Hand',
		],
	},
	CS: [
		'Income from Salary',
		'Standard Deduction u/s 16A',
		'Income from Business',
		'Net Profit',
		'Income from Other Sources',
		'Interest on Savings',
		'Interest on Deposits',
		'Total Income',
		'Deduction',
		'u/s 80C',
		'u/s 80D',
		'u/s 80TTA',
		'u/s 80TTB',
		'Taxable Income',
		'R/F u/s 288A',
	],
};
