export const suggestionCorpus = {
    T: {
        To: ["Opening Stock", "Purchase", "Carriage Inward", "Gross Profit"],
        By: ["Sales", "Closing Stock"],
    },
    PL: {
        To: [
            "Rent",
            "Salary",
            "Trade License",
            "Professional Tax",
            "Electric Charges",
            "Printing & Stationary",
            "Travel & Conveyance",
            "Accounting Charges",
            "Telephone Charges",
            "General Charges",
            "Bank Charges",
            "Net Profit",
            "Depreciation",
            "Furniture @ 10%",
            "Lighting & Fitting @ 15%",
        ],
        By: [
            "Gross Profit",
            "Interest on Savings",
            "Interest on Deposits",
            "Interest on IT Refund",
            "Interest on Capital",
        ],
    },
    BS: {
        To: [
            "Capital Account",
            "Opening Balance",
            "Last Account",
            "Net Profit",
            "Income Tax Refund",
            "Cash Drawing",
            "LIP",
            "Sundry Creditors",
            "Loans",
        ],
        By: [
            "Furniture",
            "Computer",
            "Mobile",
            "TDS",
            "Lighting & Fittings",
            "Plant & Machineries",
            "Addition",
            "Opening Balance",
            "Last Account",
            "Dep @ 10%",
            "Dep @ 15%",
            "Sundry Debtors",
            "Closing Stock",
            "Advances and Investment",
            "Cash at Bank",
            "<BankName>, <BranchName>, <AccountType> A/c - <AccountNumber>",
            "Cash in Hand",
        ],
    },
    CS: [
        "Income from Salary",
        "Standard Deduction u/s 16A",
        "Income from Business",
        "Net Profit",
        "Income from Other Sources",
        "Interest on Savings",
        "Interest on Deposits",
        "Total Income",
        "Deduction",
        "u/s 80C",
        "u/s 80D",
        "u/s 80TTA",
        "u/s 80TTB",
        "Taxable Income",
        "R/F u/s 288A",
    ],
};

export const bankAbbrev = {
    HDFC: "HDFC",
    ICICI: "ICICI",
    SBI: "State Bank of India",
    AXIS: "Axis Bank",
    BOI: "Bank of India",
    BOB: "Bank of Baroda",
    AB: "Allahabad Bank",
    IB: "Indian Bank",
};
